onboarding = false

[theme]
name = "terminal"
auto_switch = false

[experimental]
pane_history = true
kitty_graphics = true

[ui]
window_title = ""
prompt_new_tab_name = false
sidebar_start_collapsed = true
sidebar_collapsed_mode = "hidden"

[ui.sidebar.spaces]
rows = [["workspace", "git_status"], ["state_text"]]

[ui.toast]
delivery = "herdr"

[ui.toast.clipboard]
position = "bottom-right"

[keys]
prefix = "ctrl+o"
toggle_sidebar = "prefix+shift+b"
open_notification_target = ["prefix+o"]

new_tab = ["prefix+c", "prefix+ctrl+c"]
new_workspace = ["prefix+shift+c"]

previous_tab = ["prefix+p", "prefix+ctrl+p", "shift+left"]
next_tab = ["prefix+n", "prefix+ctrl+n", "shift+right"]

previous_agent = "alt+up"
next_agent = "alt+down"

focus_pane_up = ["prefix+k"]
focus_pane_down = ["prefix+j"]
focus_pane_left = ["prefix+h", "alt+left"]
focus_pane_right = ["prefix+l", "alt+right"]

# Plugins
[[keys.command]]
key = "prefix+b"
type = "plugin_action"
command = "dm4.workspace-sidebar.toggle-sidebar"
description = "toggle workspace sidebar"

[[keys.command]]
key = "shift+down"
type = "plugin_action"
command = "dm4.workspace-sidebar.next-tab"
description = "next tab across workspaces"

[[keys.command]]
key = "shift+up"
type = "plugin_action"
command = "dm4.workspace-sidebar.previous-tab"
description = "previous tab across workspaces"

# Other shortcuts
[[keys.command]]
key = "prefix+m"
type = "shell"
command = "herdr pane move $(herdr pane current | jq -r .result.pane.pane_id) --new-workspace"
description = "move pane to new workspace"
